### PR TITLE
Support React Native by adding check for window.document

### PR DESCRIPTION
**Pull request by spikebrehm**
React Native polyfills the `window` global, but it's not an actual DOM
`window` object. Thus, checking `typeof window !== 'undefined'` is not
enough for asserting that it's an _actual_ browser environment. Add a
`window.document != null` check and abstract out into an `isBrowser()`
function.

I created the minified file using UglifyJS2.

@matthewoden what do you think?

### CODE REVIEW

**Comment by lencioni** [comment]
What do you think about using an approach like fbjs does in their `canUseDOM`? https://github.com/facebook/fbjs/blob/89ffda59d923183dd34efb2622da0176ccb04d41/src/core/ExecutionEnvironment.js#L14-L18

Here it is in a package you could depend on: https://github.com/JedWatson/exenv

**Comment by spikebrehm** [comment]
Great call, will update. Rather than introducing a dependency, I'll just add that code inline.  This library as-is does not have any dependencies, and it's not clearly setup for browserify/webpack/otherwise.

**Comment by spikebrehm** [comment]
Updated.

**Comment by mikefowler** [comment]
@spikebrehm, @lencioni, is this still something we're interested in merging? Found via a TODO comment.

**Comment by spikebrehm** [comment]
Yes, we would still like to merge this so we can remove the hack on our side.

**Comment by mikefowler** [comment]
Cool. Pinging @matthewoden again to have a look.

**Comment by matthewoden** [comment]
Sorry about this folks! I guess I missed the initial notifications. Everything looks good!

**Comment by mikefowler** [comment]
Thanks, @matthewoden!

**Pull request merged**
